version: '3.5'

x-defualts: &defaults
  restart: unless-stopped
  networks:
    - chatbothub-network
  build:
    context: docker/runtime
    args:
      - mirror=$alpine_mirror
      
  depends_on:
    - redis
    - mysql
  volumes:
    - ./build:/app
    - ./config:/config

services:
  redis:
     restart: unless-stopped
     networks:
      - chatbothub-network
     image: redis:3.2-alpine

  mysql:
    restart: unless-stopped
    networks:
      - chatbothub-network
    image: mysql:5.6
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - chatbothub-mysql:/var/lib/mysql
      
  web:
    <<: *defaults
    command: ./app/server -s web
    env_file:
      - ./mysql.env
    ports:
      - '9000:9000'

  hub:
    <<: *defaults
    command: ./app/server -s hub
    ports:
      - '13142:13142'

volumes:
  chatbothub-mysql:
    external: true

networks:
  chatbothub-network:
    name: chatbothub_default
    
