version: '3.5'

x-defualts: &defaults
  restart: unless-stopped
  networks:
    - chatbothub-network
  build:
    context: docker/runtime
    args:
      - mirror=$alpine_mirror
      
  depends_on:
    - redis
    - mysql
  volumes:
    - ./build:/app
    - ./config:/config

services:
  redis:
     restart: unless-stopped
     networks:
      - chatbothub-network
     image: redis:3.2-alpine
     command: redis-server /usr/local/etc/redis/redis.conf
     volumes:
       - ./config/redis.conf:/usr/local/etc/redis/redis.conf

  mysql:
    restart: unless-stopped
    networks:
      - chatbothub-network
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - chatbothub-mysql:/var/lib/mysql
      
  web:
    <<: *defaults
    command: ./app/server -s web
    env_file:
      - ./mysql.env
      - ./rabbitmq.env
    ports:
      - '9000:9000'

  hub:
    <<: *defaults
    command: ./app/server -s hub
    ports:
      - '13142:13142'

  tasks:
    <<: *defaults
    command: ./app/server -s tasks
    env_file:
      - ./mysql.env

  streaming:
    <<: *defaults
    command: ./app/server -s streaming
    ports:
      - '13148:13148'
      
  mongo:
    restart: unless-stopped
    image: mongo
    networks:
      - chatbothub-network
    command: --smallfiles
    ports:
      - '27017:27017'

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3.7-management-alpine
    networks:
      - chatbothub-network
    env_file:
      - ./rabbitmq.env
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  chatbothub-mysql:
    external: true

networks:
  chatbothub-network:
    name: chatbothub_default
    
