version: '3.4'

x-defualts: &defaults
  restart: unless-stopped
  build: docker/runtime
  depends_on:
    # - redis
    - mysql
  volumes:
    - ./build:/app
    - ./config:/config

services:
  base:
    build: docker/runtime
    
  # redis:
  #   restart: unless-stopped
  #   image: redis:3.2-alpine

  mysql:
    restart: unless-stopped
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - chatbothub-mysql:/var/lib/mysql
      
  web:
    <<: *defaults
    command: ./app/server -s web
    env_file:
      - ./mysql.env
    ports:
      - '9000:9000'

  hub:
    <<: *defaults
    command: ./app/server -s hub
    ports:
      - '13142:13142'

volumes:
  chatbothub-mysql:
    external: true

