// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web.proto

package chatbotweb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetChatUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatUserRequest) Reset()         { *m = GetChatUserRequest{} }
func (m *GetChatUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetChatUserRequest) ProtoMessage()    {}
func (*GetChatUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{0}
}

func (m *GetChatUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatUserRequest.Unmarshal(m, b)
}
func (m *GetChatUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatUserRequest.Marshal(b, m, deterministic)
}
func (m *GetChatUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatUserRequest.Merge(m, src)
}
func (m *GetChatUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetChatUserRequest.Size(m)
}
func (m *GetChatUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatUserRequest proto.InternalMessageInfo

func (m *GetChatUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetChatUserRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetChatUserResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatUserResponse) Reset()         { *m = GetChatUserResponse{} }
func (m *GetChatUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetChatUserResponse) ProtoMessage()    {}
func (*GetChatUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1}
}

func (m *GetChatUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatUserResponse.Unmarshal(m, b)
}
func (m *GetChatUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatUserResponse.Marshal(b, m, deterministic)
}
func (m *GetChatUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatUserResponse.Merge(m, src)
}
func (m *GetChatUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetChatUserResponse.Size(m)
}
func (m *GetChatUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatUserResponse proto.InternalMessageInfo

func (m *GetChatUserResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type GetBotRequest struct {
	BotId                string   `protobuf:"bytes,1,opt,name=botId,proto3" json:"botId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBotRequest) Reset()         { *m = GetBotRequest{} }
func (m *GetBotRequest) String() string { return proto.CompactTextString(m) }
func (*GetBotRequest) ProtoMessage()    {}
func (*GetBotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{2}
}

func (m *GetBotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBotRequest.Unmarshal(m, b)
}
func (m *GetBotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBotRequest.Marshal(b, m, deterministic)
}
func (m *GetBotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBotRequest.Merge(m, src)
}
func (m *GetBotRequest) XXX_Size() int {
	return xxx_messageInfo_GetBotRequest.Size(m)
}
func (m *GetBotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBotRequest proto.InternalMessageInfo

func (m *GetBotRequest) GetBotId() string {
	if m != nil {
		return m.BotId
	}
	return ""
}

type GetBotResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBotResponse) Reset()         { *m = GetBotResponse{} }
func (m *GetBotResponse) String() string { return proto.CompactTextString(m) }
func (*GetBotResponse) ProtoMessage()    {}
func (*GetBotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{3}
}

func (m *GetBotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBotResponse.Unmarshal(m, b)
}
func (m *GetBotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBotResponse.Marshal(b, m, deterministic)
}
func (m *GetBotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBotResponse.Merge(m, src)
}
func (m *GetBotResponse) XXX_Size() int {
	return xxx_messageInfo_GetBotResponse.Size(m)
}
func (m *GetBotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBotResponse proto.InternalMessageInfo

func (m *GetBotResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ValidateTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenRequest) Reset()         { *m = ValidateTokenRequest{} }
func (m *ValidateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenRequest) ProtoMessage()    {}
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{4}
}

func (m *ValidateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenRequest.Unmarshal(m, b)
}
func (m *ValidateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenRequest.Marshal(b, m, deterministic)
}
func (m *ValidateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenRequest.Merge(m, src)
}
func (m *ValidateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenRequest.Size(m)
}
func (m *ValidateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenRequest proto.InternalMessageInfo

func (m *ValidateTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenResponse) Reset()         { *m = ValidateTokenResponse{} }
func (m *ValidateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResponse) ProtoMessage()    {}
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{5}
}

func (m *ValidateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResponse.Unmarshal(m, b)
}
func (m *ValidateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResponse.Marshal(b, m, deterministic)
}
func (m *ValidateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResponse.Merge(m, src)
}
func (m *ValidateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResponse.Size(m)
}
func (m *ValidateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResponse proto.InternalMessageInfo

func (m *ValidateTokenResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*GetChatUserRequest)(nil), "chatbotweb.GetChatUserRequest")
	proto.RegisterType((*GetChatUserResponse)(nil), "chatbotweb.GetChatUserResponse")
	proto.RegisterType((*GetBotRequest)(nil), "chatbotweb.GetBotRequest")
	proto.RegisterType((*GetBotResponse)(nil), "chatbotweb.GetBotResponse")
	proto.RegisterType((*ValidateTokenRequest)(nil), "chatbotweb.ValidateTokenRequest")
	proto.RegisterType((*ValidateTokenResponse)(nil), "chatbotweb.ValidateTokenResponse")
}

func init() { proto.RegisterFile("web.proto", fileDescriptor_461bb3ac99194e85) }

var fileDescriptor_461bb3ac99194e85 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x5f, 0x4b, 0x02, 0x41,
	0x14, 0xc5, 0xdb, 0x28, 0xcb, 0x5b, 0x16, 0x4c, 0x06, 0x3a, 0x0f, 0x69, 0x03, 0x41, 0x44, 0xac,
	0xf4, 0xe7, 0x0b, 0xb4, 0x05, 0xd2, 0x4b, 0x88, 0x94, 0x3d, 0xcf, 0xb4, 0xb7, 0x5d, 0xd1, 0x76,
	0x36, 0xf7, 0x6e, 0x83, 0x1f, 0xbd, 0xb7, 0x70, 0x6c, 0x5c, 0x33, 0xcb, 0xb7, 0x3d, 0x7b, 0xcf,
	0xfc, 0x2e, 0xe7, 0x70, 0xa1, 0x6c, 0x50, 0xf9, 0xe9, 0x48, 0x93, 0x66, 0xf0, 0x12, 0x4b, 0x52,
	0x9a, 0x0c, 0x2a, 0x5e, 0x8f, 0xb4, 0x8e, 0x86, 0xd8, 0xb2, 0x13, 0x95, 0xbf, 0xb6, 0x64, 0x32,
	0x9e, 0xda, 0xc4, 0x1d, 0xb0, 0x36, 0xd2, 0x6d, 0x2c, 0xe9, 0x29, 0xc3, 0x51, 0x17, 0xdf, 0x73,
	0xcc, 0x88, 0x71, 0xd8, 0xce, 0x33, 0x1c, 0x3d, 0xc8, 0x37, 0xac, 0x79, 0x4d, 0xef, 0xb4, 0xdc,
	0x9d, 0x69, 0xc6, 0x60, 0x83, 0xc6, 0x29, 0xd6, 0xd6, 0xed, 0x7f, 0xfb, 0x2d, 0x5a, 0x70, 0xf0,
	0x83, 0x92, 0xa5, 0x3a, 0xc9, 0x90, 0xd5, 0x60, 0x2b, 0x95, 0xe3, 0xa1, 0x96, 0xa1, 0xa5, 0xec,
	0x76, 0x9d, 0x14, 0x27, 0x50, 0x69, 0x23, 0x05, 0x9a, 0xdc, 0xc6, 0x2a, 0x6c, 0x2a, 0x4d, 0xf7,
	0xe1, 0xf7, 0xba, 0xa9, 0x10, 0x67, 0xb0, 0xe7, 0x6c, 0x2b, 0x91, 0xe7, 0x50, 0xed, 0xc9, 0x61,
	0x3f, 0x94, 0x84, 0x8f, 0x7a, 0x80, 0xc9, 0x1c, 0x99, 0x26, 0xda, 0x91, 0xad, 0x10, 0x17, 0x70,
	0xb8, 0xe0, 0x5e, 0xb5, 0xe0, 0xf2, 0xd3, 0x03, 0x98, 0x44, 0x0c, 0x34, 0x3d, 0xa3, 0x62, 0x1d,
	0xd8, 0x89, 0x8a, 0xcc, 0xec, 0xc8, 0x2f, 0x0a, 0xf7, 0x7f, 0x57, 0xca, 0x1b, 0x7f, 0xce, 0xa7,
	0x8b, 0xc5, 0x1a, 0xbb, 0x81, 0x52, 0x64, 0xd3, 0xb2, 0xfa, 0x82, 0xb9, 0x28, 0x8a, 0xf3, 0x65,
	0xa3, 0x19, 0xa2, 0x07, 0x95, 0x8f, 0xf9, 0x58, 0xac, 0x39, 0x6f, 0x5f, 0xd6, 0x0f, 0x3f, 0xfe,
	0xc7, 0xe1, 0xb8, 0xc1, 0x35, 0x34, 0x12, 0x24, 0x3f, 0x96, 0x66, 0x60, 0xfa, 0x14, 0x9b, 0x7e,
	0x12, 0xba, 0x67, 0x71, 0xae, 0x7c, 0x83, 0x2a, 0xd8, 0x2f, 0xba, 0xe9, 0x4c, 0x4e, 0xab, 0xe3,
	0xa9, 0x92, 0xbd, 0xb1, 0xab, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x7b, 0x62, 0x96, 0x97,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatBotWebClient is the client API for ChatBotWeb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatBotWebClient interface {
	GetChatUser(ctx context.Context, in *GetChatUserRequest, opts ...grpc.CallOption) (*GetChatUserResponse, error)
	GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*GetBotResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type chatBotWebClient struct {
	cc *grpc.ClientConn
}

func NewChatBotWebClient(cc *grpc.ClientConn) ChatBotWebClient {
	return &chatBotWebClient{cc}
}

func (c *chatBotWebClient) GetChatUser(ctx context.Context, in *GetChatUserRequest, opts ...grpc.CallOption) (*GetChatUserResponse, error) {
	out := new(GetChatUserResponse)
	err := c.cc.Invoke(ctx, "/chatbotweb.ChatBotWeb/getChatUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotWebClient) GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*GetBotResponse, error) {
	out := new(GetBotResponse)
	err := c.cc.Invoke(ctx, "/chatbotweb.ChatBotWeb/getBot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotWebClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, "/chatbotweb.ChatBotWeb/validateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatBotWebServer is the server API for ChatBotWeb service.
type ChatBotWebServer interface {
	GetChatUser(context.Context, *GetChatUserRequest) (*GetChatUserResponse, error)
	GetBot(context.Context, *GetBotRequest) (*GetBotResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
}

// UnimplementedChatBotWebServer can be embedded to have forward compatible implementations.
type UnimplementedChatBotWebServer struct {
}

func (*UnimplementedChatBotWebServer) GetChatUser(ctx context.Context, req *GetChatUserRequest) (*GetChatUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatUser not implemented")
}
func (*UnimplementedChatBotWebServer) GetBot(ctx context.Context, req *GetBotRequest) (*GetBotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBot not implemented")
}
func (*UnimplementedChatBotWebServer) ValidateToken(ctx context.Context, req *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}

func RegisterChatBotWebServer(s *grpc.Server, srv ChatBotWebServer) {
	s.RegisterService(&_ChatBotWeb_serviceDesc, srv)
}

func _ChatBotWeb_GetChatUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotWebServer).GetChatUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbotweb.ChatBotWeb/GetChatUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotWebServer).GetChatUser(ctx, req.(*GetChatUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotWeb_GetBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotWebServer).GetBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbotweb.ChatBotWeb/GetBot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotWebServer).GetBot(ctx, req.(*GetBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotWeb_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotWebServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbotweb.ChatBotWeb/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotWebServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatBotWeb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatbotweb.ChatBotWeb",
	HandlerType: (*ChatBotWebServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getChatUser",
			Handler:    _ChatBotWeb_GetChatUser_Handler,
		},
		{
			MethodName: "getBot",
			Handler:    _ChatBotWeb_GetBot_Handler,
		},
		{
			MethodName: "validateToken",
			Handler:    _ChatBotWeb_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web.proto",
}
