// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web.proto

package chatbotweb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetChatUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatUserRequest) Reset()         { *m = GetChatUserRequest{} }
func (m *GetChatUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetChatUserRequest) ProtoMessage()    {}
func (*GetChatUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{0}
}

func (m *GetChatUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatUserRequest.Unmarshal(m, b)
}
func (m *GetChatUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatUserRequest.Marshal(b, m, deterministic)
}
func (m *GetChatUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatUserRequest.Merge(m, src)
}
func (m *GetChatUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetChatUserRequest.Size(m)
}
func (m *GetChatUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatUserRequest proto.InternalMessageInfo

func (m *GetChatUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetChatUserRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type GetChatUserResponse struct {
	Payload              *any.Any `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatUserResponse) Reset()         { *m = GetChatUserResponse{} }
func (m *GetChatUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetChatUserResponse) ProtoMessage()    {}
func (*GetChatUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1}
}

func (m *GetChatUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatUserResponse.Unmarshal(m, b)
}
func (m *GetChatUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatUserResponse.Marshal(b, m, deterministic)
}
func (m *GetChatUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatUserResponse.Merge(m, src)
}
func (m *GetChatUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetChatUserResponse.Size(m)
}
func (m *GetChatUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatUserResponse proto.InternalMessageInfo

func (m *GetChatUserResponse) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*GetChatUserRequest)(nil), "chatbotweb.GetChatUserRequest")
	proto.RegisterType((*GetChatUserResponse)(nil), "chatbotweb.GetChatUserResponse")
}

func init() { proto.RegisterFile("web.proto", fileDescriptor_461bb3ac99194e85) }

var fileDescriptor_461bb3ac99194e85 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xad, 0x88, 0xba, 0xb3, 0x07, 0x21, 0x7a, 0x58, 0x7b, 0x70, 0xa5, 0x27, 0x4f, 0xb3,
	0xb0, 0xfa, 0x02, 0x56, 0xc5, 0x9b, 0x94, 0x82, 0x78, 0x13, 0x12, 0x77, 0x6c, 0x16, 0xd7, 0x4c,
	0x6d, 0xa6, 0x84, 0xbe, 0xbd, 0x34, 0xa5, 0x16, 0x11, 0x6f, 0xc9, 0xfc, 0xff, 0x7c, 0x7c, 0x03,
	0xb3, 0x40, 0x06, 0xeb, 0x86, 0x85, 0x15, 0xbc, 0x59, 0x2d, 0x86, 0x25, 0x90, 0x49, 0xcf, 0x2b,
	0xe6, 0x6a, 0x47, 0xab, 0x98, 0x98, 0xf6, 0x7d, 0xa5, 0x5d, 0x37, 0xd4, 0xb2, 0x7b, 0x50, 0x8f,
	0x24, 0x77, 0x56, 0xcb, 0xb3, 0xa7, 0xa6, 0xa4, 0xaf, 0x96, 0xbc, 0xa8, 0x14, 0x8e, 0x5b, 0x4f,
	0xcd, 0x93, 0xfe, 0xa4, 0x45, 0x72, 0x99, 0x5c, 0xcd, 0xca, 0x9f, 0xbf, 0x52, 0x70, 0x20, 0x5d,
	0x4d, 0x8b, 0xfd, 0x38, 0x8f, 0xef, 0xec, 0x01, 0x4e, 0x7f, 0x51, 0x7c, 0xcd, 0xce, 0x93, 0x42,
	0x38, 0xaa, 0x75, 0xb7, 0x63, 0xbd, 0x89, 0x94, 0xf9, 0xfa, 0x0c, 0x07, 0x13, 0x1c, 0x4d, 0xf0,
	0xd6, 0x75, 0xe5, 0x58, 0x5a, 0xbf, 0x02, 0xf4, 0x8c, 0x9c, 0xe5, 0x85, 0x8c, 0x2a, 0x60, 0x5e,
	0x4d, 0x50, 0x75, 0x81, 0xd3, 0x45, 0xf8, 0xd7, 0x39, 0x5d, 0xfe, 0x9b, 0x0f, 0x36, 0xd9, 0x5e,
	0x7e, 0x03, 0x4b, 0x47, 0x82, 0x56, 0x87, 0x8f, 0xb0, 0x15, 0x1b, 0xb6, 0x6e, 0x33, 0x2e, 0xd9,
	0xd6, 0x60, 0x20, 0x93, 0x9f, 0x4c, 0x02, 0x45, 0xef, 0x58, 0x24, 0xe6, 0x30, 0xca, 0x5e, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x19, 0x9f, 0x99, 0x01, 0x5d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatBotWebClient is the client API for ChatBotWeb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatBotWebClient interface {
	GetChatUser(ctx context.Context, in *GetChatUserRequest, opts ...grpc.CallOption) (*GetChatUserResponse, error)
}

type chatBotWebClient struct {
	cc *grpc.ClientConn
}

func NewChatBotWebClient(cc *grpc.ClientConn) ChatBotWebClient {
	return &chatBotWebClient{cc}
}

func (c *chatBotWebClient) GetChatUser(ctx context.Context, in *GetChatUserRequest, opts ...grpc.CallOption) (*GetChatUserResponse, error) {
	out := new(GetChatUserResponse)
	err := c.cc.Invoke(ctx, "/chatbotweb.ChatBotWeb/getChatUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatBotWebServer is the server API for ChatBotWeb service.
type ChatBotWebServer interface {
	GetChatUser(context.Context, *GetChatUserRequest) (*GetChatUserResponse, error)
}

// UnimplementedChatBotWebServer can be embedded to have forward compatible implementations.
type UnimplementedChatBotWebServer struct {
}

func (*UnimplementedChatBotWebServer) GetChatUser(ctx context.Context, req *GetChatUserRequest) (*GetChatUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatUser not implemented")
}

func RegisterChatBotWebServer(s *grpc.Server, srv ChatBotWebServer) {
	s.RegisterService(&_ChatBotWeb_serviceDesc, srv)
}

func _ChatBotWeb_GetChatUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotWebServer).GetChatUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbotweb.ChatBotWeb/GetChatUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotWebServer).GetChatUser(ctx, req.(*GetChatUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatBotWeb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatbotweb.ChatBotWeb",
	HandlerType: (*ChatBotWebServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getChatUser",
			Handler:    _ChatBotWeb_GetChatUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web.proto",
}
