// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatbothub.proto

package chatbothub

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperationReply struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationReply) Reset()         { *m = OperationReply{} }
func (m *OperationReply) String() string { return proto.CompactTextString(m) }
func (*OperationReply) ProtoMessage()    {}
func (*OperationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{0}
}

func (m *OperationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationReply.Unmarshal(m, b)
}
func (m *OperationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationReply.Marshal(b, m, deterministic)
}
func (m *OperationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationReply.Merge(m, src)
}
func (m *OperationReply) XXX_Size() int {
	return xxx_messageInfo_OperationReply.Size(m)
}
func (m *OperationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationReply.DiscardUnknown(m)
}

var xxx_messageInfo_OperationReply proto.InternalMessageInfo

func (m *OperationReply) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *OperationReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BotFilterRequest struct {
	BotId                string   `protobuf:"bytes,1,opt,name=botId,proto3" json:"botId,omitempty"`
	FilterId             string   `protobuf:"bytes,2,opt,name=filterId,proto3" json:"filterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotFilterRequest) Reset()         { *m = BotFilterRequest{} }
func (m *BotFilterRequest) String() string { return proto.CompactTextString(m) }
func (*BotFilterRequest) ProtoMessage()    {}
func (*BotFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{1}
}

func (m *BotFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotFilterRequest.Unmarshal(m, b)
}
func (m *BotFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotFilterRequest.Marshal(b, m, deterministic)
}
func (m *BotFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotFilterRequest.Merge(m, src)
}
func (m *BotFilterRequest) XXX_Size() int {
	return xxx_messageInfo_BotFilterRequest.Size(m)
}
func (m *BotFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotFilterRequest proto.InternalMessageInfo

func (m *BotFilterRequest) GetBotId() string {
	if m != nil {
		return m.BotId
	}
	return ""
}

func (m *BotFilterRequest) GetFilterId() string {
	if m != nil {
		return m.FilterId
	}
	return ""
}

type FilterCreateRequest struct {
	FilterId             string   `protobuf:"bytes,1,opt,name=filterId,proto3" json:"filterId,omitempty"`
	FilterType           string   `protobuf:"bytes,2,opt,name=filterType,proto3" json:"filterType,omitempty"`
	FilterName           string   `protobuf:"bytes,3,opt,name=filterName,proto3" json:"filterName,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterCreateRequest) Reset()         { *m = FilterCreateRequest{} }
func (m *FilterCreateRequest) String() string { return proto.CompactTextString(m) }
func (*FilterCreateRequest) ProtoMessage()    {}
func (*FilterCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{2}
}

func (m *FilterCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterCreateRequest.Unmarshal(m, b)
}
func (m *FilterCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterCreateRequest.Marshal(b, m, deterministic)
}
func (m *FilterCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterCreateRequest.Merge(m, src)
}
func (m *FilterCreateRequest) XXX_Size() int {
	return xxx_messageInfo_FilterCreateRequest.Size(m)
}
func (m *FilterCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterCreateRequest proto.InternalMessageInfo

func (m *FilterCreateRequest) GetFilterId() string {
	if m != nil {
		return m.FilterId
	}
	return ""
}

func (m *FilterCreateRequest) GetFilterType() string {
	if m != nil {
		return m.FilterType
	}
	return ""
}

func (m *FilterCreateRequest) GetFilterName() string {
	if m != nil {
		return m.FilterName
	}
	return ""
}

func (m *FilterCreateRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type FilterNextRequest struct {
	FilterId             string   `protobuf:"bytes,1,opt,name=filterId,proto3" json:"filterId,omitempty"`
	NextFilterId         string   `protobuf:"bytes,2,opt,name=nextFilterId,proto3" json:"nextFilterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterNextRequest) Reset()         { *m = FilterNextRequest{} }
func (m *FilterNextRequest) String() string { return proto.CompactTextString(m) }
func (*FilterNextRequest) ProtoMessage()    {}
func (*FilterNextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{3}
}

func (m *FilterNextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterNextRequest.Unmarshal(m, b)
}
func (m *FilterNextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterNextRequest.Marshal(b, m, deterministic)
}
func (m *FilterNextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterNextRequest.Merge(m, src)
}
func (m *FilterNextRequest) XXX_Size() int {
	return xxx_messageInfo_FilterNextRequest.Size(m)
}
func (m *FilterNextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterNextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterNextRequest proto.InternalMessageInfo

func (m *FilterNextRequest) GetFilterId() string {
	if m != nil {
		return m.FilterId
	}
	return ""
}

func (m *FilterNextRequest) GetNextFilterId() string {
	if m != nil {
		return m.NextFilterId
	}
	return ""
}

type EventRequest struct {
	EventType            string   `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           string   `protobuf:"bytes,4,opt,name=clientType,proto3" json:"clientType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{4}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *EventRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *EventRequest) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

type EventReply struct {
	EventType            string   `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           string   `protobuf:"bytes,4,opt,name=clientType,proto3" json:"clientType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventReply) Reset()         { *m = EventReply{} }
func (m *EventReply) String() string { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()    {}
func (*EventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{5}
}

func (m *EventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventReply.Unmarshal(m, b)
}
func (m *EventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventReply.Marshal(b, m, deterministic)
}
func (m *EventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReply.Merge(m, src)
}
func (m *EventReply) XXX_Size() int {
	return xxx_messageInfo_EventReply.Size(m)
}
func (m *EventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReply.DiscardUnknown(m)
}

var xxx_messageInfo_EventReply proto.InternalMessageInfo

func (m *EventReply) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *EventReply) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *EventReply) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

type BotsRequest struct {
	Logins               []string `protobuf:"bytes,1,rep,name=logins,proto3" json:"logins,omitempty"`
	BotIds               []string `protobuf:"bytes,2,rep,name=botIds,proto3" json:"botIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotsRequest) Reset()         { *m = BotsRequest{} }
func (m *BotsRequest) String() string { return proto.CompactTextString(m) }
func (*BotsRequest) ProtoMessage()    {}
func (*BotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{6}
}

func (m *BotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotsRequest.Unmarshal(m, b)
}
func (m *BotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotsRequest.Marshal(b, m, deterministic)
}
func (m *BotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotsRequest.Merge(m, src)
}
func (m *BotsRequest) XXX_Size() int {
	return xxx_messageInfo_BotsRequest.Size(m)
}
func (m *BotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotsRequest proto.InternalMessageInfo

func (m *BotsRequest) GetLogins() []string {
	if m != nil {
		return m.Logins
	}
	return nil
}

func (m *BotsRequest) GetBotIds() []string {
	if m != nil {
		return m.BotIds
	}
	return nil
}

type BotsReply struct {
	BotsInfo             []*BotsInfo `protobuf:"bytes,1,rep,name=botsInfo,proto3" json:"botsInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BotsReply) Reset()         { *m = BotsReply{} }
func (m *BotsReply) String() string { return proto.CompactTextString(m) }
func (*BotsReply) ProtoMessage()    {}
func (*BotsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{7}
}

func (m *BotsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotsReply.Unmarshal(m, b)
}
func (m *BotsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotsReply.Marshal(b, m, deterministic)
}
func (m *BotsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotsReply.Merge(m, src)
}
func (m *BotsReply) XXX_Size() int {
	return xxx_messageInfo_BotsReply.Size(m)
}
func (m *BotsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BotsReply.DiscardUnknown(m)
}

var xxx_messageInfo_BotsReply proto.InternalMessageInfo

func (m *BotsReply) GetBotsInfo() []*BotsInfo {
	if m != nil {
		return m.BotsInfo
	}
	return nil
}

type BotsInfo struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           string   `protobuf:"bytes,2,opt,name=clientType,proto3" json:"clientType,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StartAt              int64    `protobuf:"varint,4,opt,name=startAt,proto3" json:"startAt,omitempty"`
	LastPing             int64    `protobuf:"varint,5,opt,name=lastPing,proto3" json:"lastPing,omitempty"`
	Login                string   `protobuf:"bytes,6,opt,name=login,proto3" json:"login,omitempty"`
	LoginInfo            string   `protobuf:"bytes,7,opt,name=loginInfo,proto3" json:"loginInfo,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	FilterInfo           string   `protobuf:"bytes,9,opt,name=filterInfo,proto3" json:"filterInfo,omitempty"`
	BotId                string   `protobuf:"bytes,10,opt,name=botId,proto3" json:"botId,omitempty"`
	ScanUrl              string   `protobuf:"bytes,11,opt,name=scanUrl,proto3" json:"scanUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotsInfo) Reset()         { *m = BotsInfo{} }
func (m *BotsInfo) String() string { return proto.CompactTextString(m) }
func (*BotsInfo) ProtoMessage()    {}
func (*BotsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{8}
}

func (m *BotsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotsInfo.Unmarshal(m, b)
}
func (m *BotsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotsInfo.Marshal(b, m, deterministic)
}
func (m *BotsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotsInfo.Merge(m, src)
}
func (m *BotsInfo) XXX_Size() int {
	return xxx_messageInfo_BotsInfo.Size(m)
}
func (m *BotsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BotsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BotsInfo proto.InternalMessageInfo

func (m *BotsInfo) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *BotsInfo) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

func (m *BotsInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BotsInfo) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *BotsInfo) GetLastPing() int64 {
	if m != nil {
		return m.LastPing
	}
	return 0
}

func (m *BotsInfo) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *BotsInfo) GetLoginInfo() string {
	if m != nil {
		return m.LoginInfo
	}
	return ""
}

func (m *BotsInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BotsInfo) GetFilterInfo() string {
	if m != nil {
		return m.FilterInfo
	}
	return ""
}

func (m *BotsInfo) GetBotId() string {
	if m != nil {
		return m.BotId
	}
	return ""
}

func (m *BotsInfo) GetScanUrl() string {
	if m != nil {
		return m.ScanUrl
	}
	return ""
}

type BotLoginRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           string   `protobuf:"bytes,2,opt,name=clientType,proto3" json:"clientType,omitempty"`
	Login                string   `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,5,opt,name=notifyUrl,proto3" json:"notifyUrl,omitempty"`
	LoginInfo            string   `protobuf:"bytes,6,opt,name=loginInfo,proto3" json:"loginInfo,omitempty"`
	BotId                string   `protobuf:"bytes,7,opt,name=botId,proto3" json:"botId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotLoginRequest) Reset()         { *m = BotLoginRequest{} }
func (m *BotLoginRequest) String() string { return proto.CompactTextString(m) }
func (*BotLoginRequest) ProtoMessage()    {}
func (*BotLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{9}
}

func (m *BotLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotLoginRequest.Unmarshal(m, b)
}
func (m *BotLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotLoginRequest.Marshal(b, m, deterministic)
}
func (m *BotLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotLoginRequest.Merge(m, src)
}
func (m *BotLoginRequest) XXX_Size() int {
	return xxx_messageInfo_BotLoginRequest.Size(m)
}
func (m *BotLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotLoginRequest proto.InternalMessageInfo

func (m *BotLoginRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *BotLoginRequest) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

func (m *BotLoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *BotLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *BotLoginRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *BotLoginRequest) GetLoginInfo() string {
	if m != nil {
		return m.LoginInfo
	}
	return ""
}

func (m *BotLoginRequest) GetBotId() string {
	if m != nil {
		return m.BotId
	}
	return ""
}

type BotLoginReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotLoginReply) Reset()         { *m = BotLoginReply{} }
func (m *BotLoginReply) String() string { return proto.CompactTextString(m) }
func (*BotLoginReply) ProtoMessage()    {}
func (*BotLoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{10}
}

func (m *BotLoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotLoginReply.Unmarshal(m, b)
}
func (m *BotLoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotLoginReply.Marshal(b, m, deterministic)
}
func (m *BotLoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotLoginReply.Merge(m, src)
}
func (m *BotLoginReply) XXX_Size() int {
	return xxx_messageInfo_BotLoginReply.Size(m)
}
func (m *BotLoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BotLoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_BotLoginReply proto.InternalMessageInfo

func (m *BotLoginReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type BotActionRequest struct {
	ActionRequestId      string   `protobuf:"bytes,1,opt,name=actionRequestId,proto3" json:"actionRequestId,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	ActionType           string   `protobuf:"bytes,3,opt,name=actionType,proto3" json:"actionType,omitempty"`
	ActionBody           string   `protobuf:"bytes,4,opt,name=actionBody,proto3" json:"actionBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotActionRequest) Reset()         { *m = BotActionRequest{} }
func (m *BotActionRequest) String() string { return proto.CompactTextString(m) }
func (*BotActionRequest) ProtoMessage()    {}
func (*BotActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{11}
}

func (m *BotActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotActionRequest.Unmarshal(m, b)
}
func (m *BotActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotActionRequest.Marshal(b, m, deterministic)
}
func (m *BotActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotActionRequest.Merge(m, src)
}
func (m *BotActionRequest) XXX_Size() int {
	return xxx_messageInfo_BotActionRequest.Size(m)
}
func (m *BotActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotActionRequest proto.InternalMessageInfo

func (m *BotActionRequest) GetActionRequestId() string {
	if m != nil {
		return m.ActionRequestId
	}
	return ""
}

func (m *BotActionRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *BotActionRequest) GetActionType() string {
	if m != nil {
		return m.ActionType
	}
	return ""
}

func (m *BotActionRequest) GetActionBody() string {
	if m != nil {
		return m.ActionBody
	}
	return ""
}

type BotActionReply struct {
	ActionRequestId      string   `protobuf:"bytes,1,opt,name=actionRequestId,proto3" json:"actionRequestId,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotActionReply) Reset()         { *m = BotActionReply{} }
func (m *BotActionReply) String() string { return proto.CompactTextString(m) }
func (*BotActionReply) ProtoMessage()    {}
func (*BotActionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{12}
}

func (m *BotActionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotActionReply.Unmarshal(m, b)
}
func (m *BotActionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotActionReply.Marshal(b, m, deterministic)
}
func (m *BotActionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotActionReply.Merge(m, src)
}
func (m *BotActionReply) XXX_Size() int {
	return xxx_messageInfo_BotActionReply.Size(m)
}
func (m *BotActionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BotActionReply.DiscardUnknown(m)
}

var xxx_messageInfo_BotActionReply proto.InternalMessageInfo

func (m *BotActionReply) GetActionRequestId() string {
	if m != nil {
		return m.ActionRequestId
	}
	return ""
}

func (m *BotActionReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BotActionReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BotActionReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*OperationReply)(nil), "chatbothub.OperationReply")
	proto.RegisterType((*BotFilterRequest)(nil), "chatbothub.BotFilterRequest")
	proto.RegisterType((*FilterCreateRequest)(nil), "chatbothub.FilterCreateRequest")
	proto.RegisterType((*FilterNextRequest)(nil), "chatbothub.FilterNextRequest")
	proto.RegisterType((*EventRequest)(nil), "chatbothub.EventRequest")
	proto.RegisterType((*EventReply)(nil), "chatbothub.EventReply")
	proto.RegisterType((*BotsRequest)(nil), "chatbothub.BotsRequest")
	proto.RegisterType((*BotsReply)(nil), "chatbothub.BotsReply")
	proto.RegisterType((*BotsInfo)(nil), "chatbothub.BotsInfo")
	proto.RegisterType((*BotLoginRequest)(nil), "chatbothub.BotLoginRequest")
	proto.RegisterType((*BotLoginReply)(nil), "chatbothub.BotLoginReply")
	proto.RegisterType((*BotActionRequest)(nil), "chatbothub.BotActionRequest")
	proto.RegisterType((*BotActionReply)(nil), "chatbothub.BotActionReply")
}

func init() { proto.RegisterFile("chatbothub.proto", fileDescriptor_0b1f640cec0d9d68) }

var fileDescriptor_0b1f640cec0d9d68 = []byte{
	// 771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdf, 0x52, 0x13, 0x3f,
	0x14, 0x66, 0x5b, 0xfa, 0xef, 0x94, 0x1f, 0xf0, 0x8b, 0x88, 0x6b, 0x41, 0xac, 0xb9, 0xea, 0x15,
	0xc3, 0xe0, 0xa5, 0x83, 0x33, 0x2c, 0x20, 0x76, 0x46, 0x91, 0x59, 0xf1, 0x01, 0x76, 0xb7, 0xa1,
	0xdd, 0x71, 0x49, 0xea, 0x26, 0xb5, 0x94, 0xf1, 0xca, 0x19, 0x5f, 0xc0, 0xe7, 0xf0, 0x65, 0x7c,
	0x23, 0x27, 0xc9, 0x6e, 0x36, 0x5b, 0x2a, 0x32, 0x5e, 0x78, 0x97, 0xf3, 0x9d, 0xe4, 0xdb, 0xf3,
	0x9d, 0x9c, 0x73, 0xb2, 0xb0, 0x1e, 0x8d, 0x02, 0x11, 0x32, 0x31, 0x9a, 0x84, 0xbb, 0xe3, 0x94,
	0x09, 0x86, 0xa0, 0x40, 0xf0, 0x4b, 0x58, 0x7d, 0x37, 0x26, 0x69, 0x20, 0x62, 0x46, 0x7d, 0x32,
	0x4e, 0x66, 0x08, 0xc1, 0x72, 0xc4, 0x06, 0xc4, 0x75, 0xba, 0x4e, 0xaf, 0xea, 0xab, 0x35, 0x72,
	0xa1, 0x71, 0x45, 0x38, 0x0f, 0x86, 0xc4, 0xad, 0x74, 0x9d, 0x5e, 0xcb, 0xcf, 0x4d, 0x7c, 0x0c,
	0xeb, 0x1e, 0x13, 0xaf, 0xe2, 0x44, 0x90, 0xd4, 0x27, 0x9f, 0x26, 0x84, 0x0b, 0xb4, 0x01, 0xb5,
	0x90, 0x89, 0xfe, 0x40, 0x51, 0xb4, 0x7c, 0x6d, 0xa0, 0x0e, 0x34, 0x2f, 0xd5, 0xb6, 0xfe, 0x20,
	0x23, 0x31, 0x36, 0xfe, 0xe6, 0xc0, 0x03, 0xcd, 0x71, 0x94, 0x92, 0x40, 0x90, 0x9c, 0xc9, 0x3e,
	0xe3, 0x94, 0xcf, 0xa0, 0x1d, 0x00, 0xbd, 0xbe, 0x98, 0x8d, 0xf3, 0xb0, 0x2c, 0xa4, 0xf0, 0x9f,
	0x05, 0x57, 0xc4, 0xad, 0xda, 0x7e, 0x89, 0x48, 0x9d, 0x21, 0x1b, 0xcc, 0xdc, 0x65, 0xe5, 0x51,
	0x6b, 0xfc, 0x1e, 0xfe, 0xd7, 0x61, 0x9c, 0x91, 0x6b, 0x71, 0x9f, 0x20, 0x30, 0xac, 0x50, 0x72,
	0x9d, 0xe9, 0x37, 0xc2, 0x4a, 0x18, 0xfe, 0x02, 0x2b, 0x27, 0x9f, 0x09, 0x35, 0x7c, 0xdb, 0xd0,
	0x22, 0xd2, 0x56, 0x71, 0x6b, 0xc2, 0x02, 0x30, 0x61, 0x55, 0x8a, 0xb0, 0x64, 0x04, 0x51, 0x12,
	0x13, 0x2a, 0x73, 0xaa, 0x85, 0x18, 0x5b, 0xca, 0xd4, 0x6b, 0x45, 0xa7, 0xc5, 0x58, 0x08, 0xbe,
	0x01, 0xc8, 0xbe, 0x2e, 0x2f, 0xf7, 0xdf, 0x7e, 0xfb, 0x00, 0xda, 0x1e, 0x13, 0x3c, 0x17, 0xbe,
	0x09, 0xf5, 0x84, 0x0d, 0x63, 0xca, 0x5d, 0xa7, 0x5b, 0xed, 0xb5, 0xfc, 0xcc, 0x92, 0xb8, 0x2a,
	0x11, 0xee, 0x56, 0x34, 0xae, 0x2d, 0x7c, 0x00, 0x2d, 0x7d, 0x5c, 0x46, 0xbe, 0x07, 0xcd, 0x90,
	0x09, 0xde, 0xa7, 0x97, 0x4c, 0x1d, 0x6f, 0xef, 0x6f, 0xec, 0x5a, 0x95, 0xed, 0x65, 0x3e, 0xdf,
	0xec, 0xc2, 0x3f, 0x2a, 0xd0, 0xcc, 0xe1, 0x92, 0x0c, 0xe7, 0x4e, 0x19, 0x95, 0x79, 0x19, 0x32,
	0x2d, 0xb4, 0xa8, 0x21, 0xb5, 0x96, 0x1d, 0xc1, 0x45, 0x90, 0x8a, 0x43, 0xa1, 0x74, 0x57, 0xfd,
	0xdc, 0x94, 0x5f, 0x4a, 0x02, 0x2e, 0xce, 0x63, 0x3a, 0x74, 0x6b, 0xca, 0x65, 0x6c, 0xd9, 0x19,
	0x4a, 0xb3, 0x5b, 0xd7, 0x9d, 0xa1, 0x0c, 0x79, 0x29, 0x6a, 0xa1, 0xb4, 0x35, 0xf4, 0xa5, 0x18,
	0x40, 0x66, 0x87, 0x8b, 0x40, 0x4c, 0xb8, 0xdb, 0xec, 0x3a, 0xbd, 0x9a, 0x9f, 0x59, 0x45, 0x7d,
	0xab, 0x63, 0x2d, 0xbb, 0xbe, 0xd5, 0x39, 0xd3, 0x85, 0x60, 0x77, 0xa1, 0x8c, 0x3b, 0x0a, 0xe8,
	0x87, 0x34, 0x71, 0xdb, 0xba, 0x93, 0x33, 0x13, 0xff, 0x74, 0x60, 0xcd, 0x63, 0xe2, 0x8d, 0xfc,
	0xb0, 0x55, 0xfa, 0x7f, 0x9d, 0x35, 0xa3, 0xb5, 0x6a, 0x6b, 0xed, 0x40, 0x73, 0x1c, 0x70, 0x3e,
	0x65, 0xe9, 0x20, 0x2b, 0x18, 0x63, 0xcb, 0x3c, 0x50, 0x26, 0xe2, 0xcb, 0x99, 0x8c, 0xae, 0xa6,
	0xf3, 0x60, 0x80, 0x72, 0x96, 0xea, 0xf3, 0x59, 0x32, 0x6a, 0x1b, 0x96, 0x5a, 0xfc, 0x0c, 0xfe,
	0x2b, 0x24, 0xc9, 0x2a, 0x5a, 0x87, 0xea, 0x15, 0x1f, 0x66, 0x5a, 0xe4, 0x12, 0x7f, 0x77, 0xd4,
	0x04, 0x3b, 0x8c, 0xf4, 0x04, 0xd4, 0xba, 0x7b, 0xb0, 0x16, 0xd8, 0x80, 0x91, 0x3f, 0x0f, 0x17,
	0x2a, 0x2b, 0xb6, 0xca, 0x1d, 0x00, 0xbd, 0x51, 0xe5, 0x26, 0x9b, 0x3d, 0x05, 0x52, 0xf8, 0xbd,
	0x62, 0x02, 0x59, 0x08, 0xbe, 0x81, 0x55, 0x2b, 0x26, 0x19, 0xf8, 0xfd, 0x23, 0x92, 0x37, 0x3c,
	0x89, 0x22, 0xc2, 0xb9, 0x8a, 0xa9, 0xe9, 0xe7, 0x66, 0x2e, 0xbe, 0x6a, 0xc4, 0x2f, 0x9a, 0x81,
	0xfb, 0x5f, 0x97, 0x01, 0x8e, 0x46, 0x81, 0xf0, 0x98, 0x78, 0x3d, 0x09, 0xd1, 0x09, 0xb4, 0xd5,
	0xfc, 0xb8, 0x98, 0x50, 0x4a, 0x12, 0xe4, 0xda, 0x4d, 0x67, 0x8f, 0xb5, 0xce, 0xe6, 0x02, 0xcf,
	0x38, 0x99, 0xe1, 0xa5, 0x9e, 0xb3, 0xe7, 0xa0, 0x17, 0xd0, 0x38, 0x25, 0x92, 0x93, 0xa3, 0x47,
	0xf3, 0x7d, 0x9b, 0x33, 0x3c, 0xbc, 0xed, 0x50, 0x04, 0xe8, 0x58, 0x35, 0xb2, 0xba, 0x46, 0xb4,
	0x35, 0xb7, 0xc9, 0xae, 0xd7, 0xce, 0xe3, 0xc5, 0x4e, 0xcd, 0x72, 0xaa, 0xc6, 0x89, 0x4e, 0x2a,
	0xda, 0x9e, 0xdb, 0x59, 0xba, 0xff, 0x4e, 0xe7, 0x37, 0x5e, 0x9b, 0x48, 0xcf, 0xf7, 0x5b, 0x44,
	0xa5, 0xa7, 0xb0, 0x4c, 0x54, 0x7e, 0x68, 0xf1, 0x12, 0x7a, 0x0b, 0x2b, 0xf6, 0xab, 0x87, 0x9e,
	0xda, 0xbb, 0x17, 0xbc, 0x87, 0x7f, 0xa0, 0xeb, 0x03, 0x14, 0xaf, 0x17, 0x7a, 0x72, 0x9b, 0xcc,
	0x7a, 0xd5, 0xee, 0xa6, 0xf2, 0xf6, 0x60, 0x8b, 0x12, 0xb1, 0x3b, 0x0a, 0xa6, 0x1f, 0xa7, 0xb1,
	0x18, 0x4d, 0x63, 0x3a, 0xb0, 0xf6, 0x7b, 0x6b, 0x45, 0x81, 0x9c, 0xcb, 0x5f, 0x8a, 0x73, 0x27,
	0xac, 0xab, 0x7f, 0x8b, 0xe7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xf9, 0x50, 0x0e, 0x6f,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatBotHubClient is the client API for ChatBotHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatBotHubClient interface {
	// bots only use eventtunnel to communicate
	EventTunnel(ctx context.Context, opts ...grpc.CallOption) (ChatBotHub_EventTunnelClient, error)
	// below are for internal web api
	GetBots(ctx context.Context, in *BotsRequest, opts ...grpc.CallOption) (*BotsReply, error)
	BotLogin(ctx context.Context, in *BotLoginRequest, opts ...grpc.CallOption) (*BotLoginReply, error)
	BotAction(ctx context.Context, in *BotActionRequest, opts ...grpc.CallOption) (*BotActionReply, error)
	BotFilter(ctx context.Context, in *BotFilterRequest, opts ...grpc.CallOption) (*OperationReply, error)
	FilterCreate(ctx context.Context, in *FilterCreateRequest, opts ...grpc.CallOption) (*OperationReply, error)
	FilterNext(ctx context.Context, in *FilterNextRequest, opts ...grpc.CallOption) (*OperationReply, error)
}

type chatBotHubClient struct {
	cc *grpc.ClientConn
}

func NewChatBotHubClient(cc *grpc.ClientConn) ChatBotHubClient {
	return &chatBotHubClient{cc}
}

func (c *chatBotHubClient) EventTunnel(ctx context.Context, opts ...grpc.CallOption) (ChatBotHub_EventTunnelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatBotHub_serviceDesc.Streams[0], "/chatbothub.ChatBotHub/EventTunnel", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatBotHubEventTunnelClient{stream}
	return x, nil
}

type ChatBotHub_EventTunnelClient interface {
	Send(*EventRequest) error
	Recv() (*EventReply, error)
	grpc.ClientStream
}

type chatBotHubEventTunnelClient struct {
	grpc.ClientStream
}

func (x *chatBotHubEventTunnelClient) Send(m *EventRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatBotHubEventTunnelClient) Recv() (*EventReply, error) {
	m := new(EventReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatBotHubClient) GetBots(ctx context.Context, in *BotsRequest, opts ...grpc.CallOption) (*BotsReply, error) {
	out := new(BotsReply)
	err := c.cc.Invoke(ctx, "/chatbothub.ChatBotHub/GetBots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotHubClient) BotLogin(ctx context.Context, in *BotLoginRequest, opts ...grpc.CallOption) (*BotLoginReply, error) {
	out := new(BotLoginReply)
	err := c.cc.Invoke(ctx, "/chatbothub.ChatBotHub/BotLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotHubClient) BotAction(ctx context.Context, in *BotActionRequest, opts ...grpc.CallOption) (*BotActionReply, error) {
	out := new(BotActionReply)
	err := c.cc.Invoke(ctx, "/chatbothub.ChatBotHub/BotAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotHubClient) BotFilter(ctx context.Context, in *BotFilterRequest, opts ...grpc.CallOption) (*OperationReply, error) {
	out := new(OperationReply)
	err := c.cc.Invoke(ctx, "/chatbothub.ChatBotHub/BotFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotHubClient) FilterCreate(ctx context.Context, in *FilterCreateRequest, opts ...grpc.CallOption) (*OperationReply, error) {
	out := new(OperationReply)
	err := c.cc.Invoke(ctx, "/chatbothub.ChatBotHub/FilterCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotHubClient) FilterNext(ctx context.Context, in *FilterNextRequest, opts ...grpc.CallOption) (*OperationReply, error) {
	out := new(OperationReply)
	err := c.cc.Invoke(ctx, "/chatbothub.ChatBotHub/FilterNext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatBotHubServer is the server API for ChatBotHub service.
type ChatBotHubServer interface {
	// bots only use eventtunnel to communicate
	EventTunnel(ChatBotHub_EventTunnelServer) error
	// below are for internal web api
	GetBots(context.Context, *BotsRequest) (*BotsReply, error)
	BotLogin(context.Context, *BotLoginRequest) (*BotLoginReply, error)
	BotAction(context.Context, *BotActionRequest) (*BotActionReply, error)
	BotFilter(context.Context, *BotFilterRequest) (*OperationReply, error)
	FilterCreate(context.Context, *FilterCreateRequest) (*OperationReply, error)
	FilterNext(context.Context, *FilterNextRequest) (*OperationReply, error)
}

func RegisterChatBotHubServer(s *grpc.Server, srv ChatBotHubServer) {
	s.RegisterService(&_ChatBotHub_serviceDesc, srv)
}

func _ChatBotHub_EventTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatBotHubServer).EventTunnel(&chatBotHubEventTunnelServer{stream})
}

type ChatBotHub_EventTunnelServer interface {
	Send(*EventReply) error
	Recv() (*EventRequest, error)
	grpc.ServerStream
}

type chatBotHubEventTunnelServer struct {
	grpc.ServerStream
}

func (x *chatBotHubEventTunnelServer) Send(m *EventReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatBotHubEventTunnelServer) Recv() (*EventRequest, error) {
	m := new(EventRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatBotHub_GetBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotHubServer).GetBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbothub.ChatBotHub/GetBots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotHubServer).GetBots(ctx, req.(*BotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotHub_BotLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotHubServer).BotLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbothub.ChatBotHub/BotLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotHubServer).BotLogin(ctx, req.(*BotLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotHub_BotAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotHubServer).BotAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbothub.ChatBotHub/BotAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotHubServer).BotAction(ctx, req.(*BotActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotHub_BotFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotHubServer).BotFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbothub.ChatBotHub/BotFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotHubServer).BotFilter(ctx, req.(*BotFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotHub_FilterCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotHubServer).FilterCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbothub.ChatBotHub/FilterCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotHubServer).FilterCreate(ctx, req.(*FilterCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotHub_FilterNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotHubServer).FilterNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbothub.ChatBotHub/FilterNext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotHubServer).FilterNext(ctx, req.(*FilterNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatBotHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatbothub.ChatBotHub",
	HandlerType: (*ChatBotHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBots",
			Handler:    _ChatBotHub_GetBots_Handler,
		},
		{
			MethodName: "BotLogin",
			Handler:    _ChatBotHub_BotLogin_Handler,
		},
		{
			MethodName: "BotAction",
			Handler:    _ChatBotHub_BotAction_Handler,
		},
		{
			MethodName: "BotFilter",
			Handler:    _ChatBotHub_BotFilter_Handler,
		},
		{
			MethodName: "FilterCreate",
			Handler:    _ChatBotHub_FilterCreate_Handler,
		},
		{
			MethodName: "FilterNext",
			Handler:    _ChatBotHub_FilterNext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventTunnel",
			Handler:       _ChatBotHub_EventTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chatbothub.proto",
}
