// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatbothub.proto

package chatbothub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventRequest struct {
	EventType            string   `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           string   `protobuf:"bytes,4,opt,name=clientType,proto3" json:"clientType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{0}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *EventRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *EventRequest) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

type EventReply struct {
	EventType            string   `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           string   `protobuf:"bytes,4,opt,name=clientType,proto3" json:"clientType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventReply) Reset()         { *m = EventReply{} }
func (m *EventReply) String() string { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()    {}
func (*EventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{1}
}

func (m *EventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventReply.Unmarshal(m, b)
}
func (m *EventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventReply.Marshal(b, m, deterministic)
}
func (m *EventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReply.Merge(m, src)
}
func (m *EventReply) XXX_Size() int {
	return xxx_messageInfo_EventReply.Size(m)
}
func (m *EventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReply.DiscardUnknown(m)
}

var xxx_messageInfo_EventReply proto.InternalMessageInfo

func (m *EventReply) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *EventReply) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *EventReply) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

type BotsRequest struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotsRequest) Reset()         { *m = BotsRequest{} }
func (m *BotsRequest) String() string { return proto.CompactTextString(m) }
func (*BotsRequest) ProtoMessage()    {}
func (*BotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{2}
}

func (m *BotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotsRequest.Unmarshal(m, b)
}
func (m *BotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotsRequest.Marshal(b, m, deterministic)
}
func (m *BotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotsRequest.Merge(m, src)
}
func (m *BotsRequest) XXX_Size() int {
	return xxx_messageInfo_BotsRequest.Size(m)
}
func (m *BotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotsRequest proto.InternalMessageInfo

func (m *BotsRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type BotsReply struct {
	BotsInfo             []*BotsInfo `protobuf:"bytes,1,rep,name=botsInfo,proto3" json:"botsInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BotsReply) Reset()         { *m = BotsReply{} }
func (m *BotsReply) String() string { return proto.CompactTextString(m) }
func (*BotsReply) ProtoMessage()    {}
func (*BotsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{3}
}

func (m *BotsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotsReply.Unmarshal(m, b)
}
func (m *BotsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotsReply.Marshal(b, m, deterministic)
}
func (m *BotsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotsReply.Merge(m, src)
}
func (m *BotsReply) XXX_Size() int {
	return xxx_messageInfo_BotsReply.Size(m)
}
func (m *BotsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BotsReply.DiscardUnknown(m)
}

var xxx_messageInfo_BotsReply proto.InternalMessageInfo

func (m *BotsReply) GetBotsInfo() []*BotsInfo {
	if m != nil {
		return m.BotsInfo
	}
	return nil
}

type BotsInfo struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           string   `protobuf:"bytes,2,opt,name=clientType,proto3" json:"clientType,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StartAt              int64    `protobuf:"varint,4,opt,name=startAt,proto3" json:"startAt,omitempty"`
	LastPing             int64    `protobuf:"varint,5,opt,name=lastPing,proto3" json:"lastPing,omitempty"`
	Login                string   `protobuf:"bytes,6,opt,name=login,proto3" json:"login,omitempty"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	FilterInfo           string   `protobuf:"bytes,8,opt,name=filterInfo,proto3" json:"filterInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotsInfo) Reset()         { *m = BotsInfo{} }
func (m *BotsInfo) String() string { return proto.CompactTextString(m) }
func (*BotsInfo) ProtoMessage()    {}
func (*BotsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{4}
}

func (m *BotsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotsInfo.Unmarshal(m, b)
}
func (m *BotsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotsInfo.Marshal(b, m, deterministic)
}
func (m *BotsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotsInfo.Merge(m, src)
}
func (m *BotsInfo) XXX_Size() int {
	return xxx_messageInfo_BotsInfo.Size(m)
}
func (m *BotsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BotsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BotsInfo proto.InternalMessageInfo

func (m *BotsInfo) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *BotsInfo) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

func (m *BotsInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BotsInfo) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *BotsInfo) GetLastPing() int64 {
	if m != nil {
		return m.LastPing
	}
	return 0
}

func (m *BotsInfo) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *BotsInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BotsInfo) GetFilterInfo() string {
	if m != nil {
		return m.FilterInfo
	}
	return ""
}

type LoginBotRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientType           string   `protobuf:"bytes,2,opt,name=clientType,proto3" json:"clientType,omitempty"`
	Login                string   `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,5,opt,name=notifyUrl,proto3" json:"notifyUrl,omitempty"`
	LoginInfo            string   `protobuf:"bytes,6,opt,name=loginInfo,proto3" json:"loginInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginBotRequest) Reset()         { *m = LoginBotRequest{} }
func (m *LoginBotRequest) String() string { return proto.CompactTextString(m) }
func (*LoginBotRequest) ProtoMessage()    {}
func (*LoginBotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{5}
}

func (m *LoginBotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginBotRequest.Unmarshal(m, b)
}
func (m *LoginBotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginBotRequest.Marshal(b, m, deterministic)
}
func (m *LoginBotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginBotRequest.Merge(m, src)
}
func (m *LoginBotRequest) XXX_Size() int {
	return xxx_messageInfo_LoginBotRequest.Size(m)
}
func (m *LoginBotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginBotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginBotRequest proto.InternalMessageInfo

func (m *LoginBotRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *LoginBotRequest) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

func (m *LoginBotRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginBotRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginBotRequest) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *LoginBotRequest) GetLoginInfo() string {
	if m != nil {
		return m.LoginInfo
	}
	return ""
}

type LoginBotReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginBotReply) Reset()         { *m = LoginBotReply{} }
func (m *LoginBotReply) String() string { return proto.CompactTextString(m) }
func (*LoginBotReply) ProtoMessage()    {}
func (*LoginBotReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b1f640cec0d9d68, []int{6}
}

func (m *LoginBotReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginBotReply.Unmarshal(m, b)
}
func (m *LoginBotReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginBotReply.Marshal(b, m, deterministic)
}
func (m *LoginBotReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginBotReply.Merge(m, src)
}
func (m *LoginBotReply) XXX_Size() int {
	return xxx_messageInfo_LoginBotReply.Size(m)
}
func (m *LoginBotReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginBotReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginBotReply proto.InternalMessageInfo

func (m *LoginBotReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*EventRequest)(nil), "chatbothub.EventRequest")
	proto.RegisterType((*EventReply)(nil), "chatbothub.EventReply")
	proto.RegisterType((*BotsRequest)(nil), "chatbothub.BotsRequest")
	proto.RegisterType((*BotsReply)(nil), "chatbothub.BotsReply")
	proto.RegisterType((*BotsInfo)(nil), "chatbothub.BotsInfo")
	proto.RegisterType((*LoginBotRequest)(nil), "chatbothub.LoginBotRequest")
	proto.RegisterType((*LoginBotReply)(nil), "chatbothub.LoginBotReply")
}

func init() { proto.RegisterFile("chatbothub.proto", fileDescriptor_0b1f640cec0d9d68) }

var fileDescriptor_0b1f640cec0d9d68 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0x64, 0xeb, 0x26, 0x71, 0x5e, 0x40, 0xad, 0x56, 0xa5, 0x2c, 0x29, 0x42, 0xc1, 0x12, 0x52,
	0x4e, 0x51, 0x54, 0x8e, 0x88, 0x03, 0x86, 0x0a, 0x2a, 0x71, 0x88, 0xac, 0xf2, 0x03, 0xec, 0x64,
	0x13, 0x5b, 0xb8, 0xbb, 0xc6, 0xfb, 0x4c, 0x64, 0xc4, 0x3f, 0xe3, 0x7f, 0x70, 0xe4, 0xb7, 0xa0,
	0x7d, 0xfe, 0x24, 0x54, 0x5c, 0x90, 0xb8, 0xed, 0xcc, 0xac, 0x66, 0x67, 0xf2, 0x5e, 0x0c, 0xa7,
	0xeb, 0x38, 0xc4, 0x48, 0x63, 0x5c, 0x44, 0x8b, 0x2c, 0xd7, 0xa8, 0x39, 0x74, 0x8c, 0xf7, 0x0d,
	0xee, 0x5f, 0x7d, 0x91, 0x0a, 0x03, 0xf9, 0xb9, 0x90, 0x06, 0xf9, 0x13, 0x18, 0x4b, 0x8b, 0x6f,
	0xca, 0x4c, 0x0a, 0x36, 0x63, 0xf3, 0x71, 0xd0, 0x11, 0x9c, 0xc3, 0x71, 0xa4, 0x37, 0xa5, 0x38,
	0x22, 0x81, 0xce, 0x7c, 0x0a, 0xee, 0x3a, 0x4d, 0xa4, 0xc2, 0xeb, 0x8d, 0x70, 0x88, 0x6f, 0x31,
	0x7f, 0x0a, 0x50, 0x9d, 0xc9, 0xee, 0x98, 0xd4, 0x1e, 0xe3, 0x7d, 0x05, 0xa8, 0x5f, 0xcf, 0xd2,
	0xf2, 0x3f, 0xbf, 0xfd, 0x1c, 0x26, 0xbe, 0x46, 0xd3, 0x14, 0x3f, 0x87, 0xa1, 0x91, 0xeb, 0x5c,
	0x62, 0xfd, 0x72, 0x8d, 0xbc, 0x57, 0x30, 0xae, 0xae, 0xd9, 0x84, 0x4b, 0x70, 0x23, 0x8d, 0xe6,
	0x5a, 0x6d, 0xb5, 0x60, 0x33, 0x67, 0x3e, 0xb9, 0x3c, 0x5b, 0xf4, 0x7e, 0x5e, 0xbf, 0xd6, 0x82,
	0xf6, 0x96, 0xf7, 0x93, 0x81, 0xdb, 0xd0, 0xbf, 0xc5, 0x65, 0x7f, 0x8d, 0x7b, 0x74, 0x18, 0xd7,
	0xd6, 0x57, 0xe1, 0xad, 0xac, 0x6b, 0xd2, 0x99, 0x0b, 0x18, 0x19, 0x0c, 0x73, 0x7c, 0x8d, 0xd4,
	0xcf, 0x09, 0x1a, 0x68, 0x5f, 0x4a, 0x43, 0x83, 0xab, 0x44, 0xed, 0xc4, 0x80, 0xa4, 0x16, 0xf3,
	0x33, 0x18, 0xa4, 0x7a, 0x97, 0x28, 0x31, 0x24, 0xab, 0x0a, 0x50, 0x7f, 0x0c, 0xb1, 0x30, 0x62,
	0x34, 0x63, 0xf3, 0x41, 0x50, 0x23, 0x9b, 0x6b, 0x9b, 0xa4, 0x28, 0x73, 0x2a, 0xed, 0x56, 0xb9,
	0x3a, 0xc6, 0xfb, 0xce, 0xe0, 0xe4, 0x83, 0x75, 0xf0, 0x75, 0xbb, 0x44, 0xff, 0xd2, 0xb3, 0x4d,
	0xe7, 0xf4, 0xd3, 0x4d, 0xc1, 0xcd, 0x42, 0x63, 0xf6, 0x3a, 0xdf, 0xd4, 0xa3, 0x6c, 0xb1, 0x5d,
	0x1b, 0xa5, 0x31, 0xd9, 0x96, 0x1f, 0xf3, 0x94, 0xca, 0x8e, 0x83, 0x8e, 0xb0, 0x2a, 0x59, 0x50,
	0xfc, 0xaa, 0x71, 0x47, 0x78, 0xcf, 0xe0, 0x41, 0x17, 0xde, 0x4e, 0xf8, 0x14, 0x9c, 0x5b, 0xb3,
	0xab, 0x53, 0xdb, 0xe3, 0xe5, 0x0f, 0x06, 0xf0, 0x26, 0x0e, 0xd1, 0xd7, 0xf8, 0xbe, 0x88, 0xf8,
	0x15, 0x4c, 0x68, 0x65, 0x6f, 0x0a, 0xa5, 0x64, 0xca, 0x45, 0x7f, 0xfe, 0xfd, 0x7f, 0xd2, 0xf4,
	0xfc, 0x0e, 0x25, 0x4b, 0x4b, 0xef, 0xde, 0x9c, 0x2d, 0x19, 0x7f, 0x09, 0xa3, 0x77, 0xd2, 0x7a,
	0x1a, 0xfe, 0xe8, 0x70, 0x85, 0x1a, 0x87, 0x87, 0x7f, 0x0a, 0x64, 0xc0, 0xdf, 0x82, 0xdb, 0xa4,
	0xe6, 0x17, 0xfd, 0x4b, 0x07, 0x83, 0x98, 0x3e, 0xbe, 0x5b, 0x24, 0x17, 0x7f, 0x09, 0x17, 0x4a,
	0xe2, 0x22, 0x0e, 0xf7, 0x9f, 0xf6, 0x09, 0xc6, 0xfb, 0x44, 0x6d, 0x7a, 0xd7, 0xfd, 0x93, 0xae,
	0xf4, 0xca, 0x7e, 0x36, 0x56, 0x2c, 0x1a, 0xd2, 0xf7, 0xe3, 0xc5, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfc, 0x9e, 0x82, 0x72, 0x53, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatBotHubClient is the client API for ChatBotHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatBotHubClient interface {
	// bots only use eventtunnel to communicate
	EventTunnel(ctx context.Context, opts ...grpc.CallOption) (ChatBotHub_EventTunnelClient, error)
	// below are for internal web api
	GetBots(ctx context.Context, in *BotsRequest, opts ...grpc.CallOption) (*BotsReply, error)
	LoginBot(ctx context.Context, in *LoginBotRequest, opts ...grpc.CallOption) (*LoginBotReply, error)
}

type chatBotHubClient struct {
	cc *grpc.ClientConn
}

func NewChatBotHubClient(cc *grpc.ClientConn) ChatBotHubClient {
	return &chatBotHubClient{cc}
}

func (c *chatBotHubClient) EventTunnel(ctx context.Context, opts ...grpc.CallOption) (ChatBotHub_EventTunnelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatBotHub_serviceDesc.Streams[0], "/chatbothub.ChatBotHub/EventTunnel", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatBotHubEventTunnelClient{stream}
	return x, nil
}

type ChatBotHub_EventTunnelClient interface {
	Send(*EventRequest) error
	Recv() (*EventReply, error)
	grpc.ClientStream
}

type chatBotHubEventTunnelClient struct {
	grpc.ClientStream
}

func (x *chatBotHubEventTunnelClient) Send(m *EventRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatBotHubEventTunnelClient) Recv() (*EventReply, error) {
	m := new(EventReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatBotHubClient) GetBots(ctx context.Context, in *BotsRequest, opts ...grpc.CallOption) (*BotsReply, error) {
	out := new(BotsReply)
	err := c.cc.Invoke(ctx, "/chatbothub.ChatBotHub/GetBots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotHubClient) LoginBot(ctx context.Context, in *LoginBotRequest, opts ...grpc.CallOption) (*LoginBotReply, error) {
	out := new(LoginBotReply)
	err := c.cc.Invoke(ctx, "/chatbothub.ChatBotHub/LoginBot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatBotHubServer is the server API for ChatBotHub service.
type ChatBotHubServer interface {
	// bots only use eventtunnel to communicate
	EventTunnel(ChatBotHub_EventTunnelServer) error
	// below are for internal web api
	GetBots(context.Context, *BotsRequest) (*BotsReply, error)
	LoginBot(context.Context, *LoginBotRequest) (*LoginBotReply, error)
}

func RegisterChatBotHubServer(s *grpc.Server, srv ChatBotHubServer) {
	s.RegisterService(&_ChatBotHub_serviceDesc, srv)
}

func _ChatBotHub_EventTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatBotHubServer).EventTunnel(&chatBotHubEventTunnelServer{stream})
}

type ChatBotHub_EventTunnelServer interface {
	Send(*EventReply) error
	Recv() (*EventRequest, error)
	grpc.ServerStream
}

type chatBotHubEventTunnelServer struct {
	grpc.ServerStream
}

func (x *chatBotHubEventTunnelServer) Send(m *EventReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatBotHubEventTunnelServer) Recv() (*EventRequest, error) {
	m := new(EventRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatBotHub_GetBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotHubServer).GetBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbothub.ChatBotHub/GetBots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotHubServer).GetBots(ctx, req.(*BotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotHub_LoginBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotHubServer).LoginBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbothub.ChatBotHub/LoginBot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotHubServer).LoginBot(ctx, req.(*LoginBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatBotHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatbothub.ChatBotHub",
	HandlerType: (*ChatBotHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBots",
			Handler:    _ChatBotHub_GetBots_Handler,
		},
		{
			MethodName: "LoginBot",
			Handler:    _ChatBotHub_LoginBot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventTunnel",
			Handler:       _ChatBotHub_EventTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chatbothub.proto",
}
